---
title: "Seconday Pipeline (Archive)"
author: "Ashkan Zareie"
date: "3/29/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

--- Secondary pipeline / secondary approach to analysis ---  
This is currently only used to generate BPC and TIC plots  
MSnbase is used to load the data, but at the core of the pipeline xcms is used to do everything else.  

```{r OnDiskMSnExp / MSnbase}
pos.mzxml <- pos.mzml

## phenodata
# s_groups <- rep("Mouse1", length(pos.mzxml))
# s_groups[grep(pos.mzxml, pattern = "Mouse2")] <- "Mouse2"
# s_groups[grep(pos.mzxml, pattern = "Mouse5")] <- "Mouse5"

s_groups <- sampclass(xsg.gaus)

## Define a data.frame that can be used as phenodata
pheno <- data.frame(sample_name = sub(basename(pos.mzxml), pattern = ".mzML", replacement = "", fixed = TRUE),
                    sample_group = s_groups, stringsAsFactors = FALSE)

MSn.set.exp <- readMSData2(pos.mzxml, pdata = new("NAnnotatedDataFrame", pheno))

rtime(MSn.set.exp[[1]]) ### retention time of the first spectrum
rtime(MSn.set.exp[[100]]) ### retention time of the 100th spectrum
mz(MSn.set.exp[[1]]) ### mz values of the first spectrum
head(mz(MSn.set.exp[[1]]))
head(intensity(MSn.set.exp[[1]]))
intensity(MSn.set.exp[[1]]) ### intensity values of the first spectrum
head(tic(MSn.set.exp)) ### the total ion current, as reported in the original raw data file

head(fromFile(MSn.set.exp)) ### fromFile method returns the index of the file that the spectrum originates from.
fromFile(MSn.set.exp[[15000]]) ### index of the file containing the 15000th spectrum

#MSnbase::plot(MSn.set.exp[[5000]]) ### plotting the 5000th spectrum
```

```{r TIC plot}
## Extract the TIC (Total Ion Current) and retention times, and split them by file.
tics <- split(tic(MSn.set.exp), f = fromFile(MSn.set.exp))
rts <- split(rtime(MSn.set.exp), f = fromFile(MSn.set.exp))

## Define the color for each sample
sample_colors <- brewer.pal(2, "Set1")[1:2]
names(sample_colors) <- unique(s_groups)
cols <- paste0(sample_colors[pData(MSn.set.exp)$sample_group], 80)

exp.polarity <- as.character()
if(gsub("^.*/","",dirname(path.pos[1])) == "pos") {exp.polarity <- "ESI+"}
if(gsub("^.*/","",dirname(path.pos[1])) == "neg") {exp.polarity <- "ESI-"}
#pdf(paste0("TIC_Plot_", basename(path.pos[[1]]), "_", exp.polarity, ".pdf"))
plot(3, 3, pch = NA, xlim = range(rts), ylim = range(tics), main = paste0("Total Ion Current (", basename(path.pos[[1]]), " ", exp.polarity, " samples)"),
     xlab = "RT (retention time)", ylab = "intensity")
tmp <- mapply(rts, tics, cols, FUN = function(x, y, col) {
    points(x = x, y = y, col = col, type = "l")
})
legend("topleft", col = sample_colors, legend = names(sample_colors), lty = 1)
#dev.off()
```

```{r BPC plot}
chrs <- extractChromatograms(MSn.set.exp, aggregationFun = "max")

#pdf(paste0("BPC_Plot_", basename(path.pos[[1]]), "_", exp.polarity, ".pdf"))
plotChromatogram(
    chrs,
    col = paste0(sample_colors[pData(MSn.set.exp)$sample_group], 80), main=paste0("Base Peak Chromatogram (", basename(path.pos[[1]]), " ", exp.polarity, " samples)"))
legend("topleft", col = sample_colors, legend = names(sample_colors), lty = 1)
#dev.off()
```

```{r Inspect the data}
subs <- filterFile(filterRt(MSn.set.exp, rt = c(350,400)), file = 1) ### choose file and rt range

## Extract the Spectrum
spctr <- spectra(subs)[[1]]
plot(mz(spctr), intensity(spctr), type = "h", xlab = "mz", ylab = "intensity", main=c("rt=", spctr@rt))
```

peaks intensities are in columns  
"into" (integrated peak signal)  
"maxo" (maximum signal at the peak’s apex)  
```{r Peak detection, cache = TRUE}
#cwp <- CentWavePredIsoParam(ppm=30)
cwp <- MassifquantParam(ppm = 30, snthresh = 40, prefilter = c(3, 50000), noise = 12000, withWave = TRUE, peakwidth = c(15, 45))
msn.chpeaks <- findChromPeaks(MSn.set.exp, param = cwp)
msn.chpeaks
head(chromPeaks(msn.chpeaks))
detected.peaks <- chromPeaks(msn.chpeaks)
table(detected.peaks[,"sample"]) ###Number of peaks per sample
table(detected.peaks[,"sample"])/sum(detected.peaks[,"sample"])
```

```{r Highlighting detected peaks, eval=FALSE}
chromPeaks(msn.chpeaks, mz = 316.1165)
chrs <- extractChromatograms(msn.chpeaks, mz = 316.1165, rt = 2.992)

#plotChromatogram(chrs,
#         col = paste0(sample_colors[pData(msn.chpeaks)$sample_group], 80))
#highlightChromPeaks(
#    msn.chpeaks, rt = 2.992, mz = 316.1165,
#    border = paste0(sample_colors[pData(msn.chpeaks)$sample_group], 40))
```

```{r Adjust retention time, eval=FALSE}
msn.rt <- adjustRtime(msn.chpeaks, param = ObiwarpParam())
hasAdjustedRtime(msn.rt)
head(rtime(msn.rt)) ###Adjusted retention times
head(rtime(msn.rt, adjusted = FALSE)) ###Raw retention times

####grouping of chromatographic peaks within and between samples. 
msn.rt.g <- groupChromPeaks(msn.rt, param = PeakDensityParam())
plotAdjustedRtime(msn.rt.g)

chrs <- extractChromatograms(msn.rt.g, aggregationFun = "max")
rt_raw <- rtime(msn.rt.g, adjusted = FALSE, bySample = TRUE)
ints <- lapply(chrs, intensity)
par(mfrow = c(3, 1), mar = c(0.5, 4, 1, 0.5))
plot(3, 3, pch = NA, xlab = "", ylab = "base peak intensity", xaxt = "n",
     main = "before adjustment", xlim = range(rt_raw), ylim = range(ints))
cols <- paste0(sample_colors[pData(msn.rt.g)$sample_group], 80)
tmp <- mapply(rt_raw, ints, cols, FUN = function(x, y, col) {
    points(x, y, col = col, type = "l")
})
plotChromatogram(chrs, main = "after adjustment", col = cols, xaxt = "n")
par(mar = c(4, 4, 0.5, 0.5))
plotAdjustedRtime(msn.rt.g, col = cols)
```

```{r Filling in missing peaks and Producing Peakimage (General visualizations of peak detection results), eval=FALSE}
head(featureValues(msn.rt.g, value = "into"))
msn.rt.g <- fillChromPeaks(msn.rt.g)
head(featureValues(msn.rt.g, value = "into"))
featureDefinitions(msn.rt.g)

pdf(paste0(basename(path.pos[[1]]), "_", exp.polarity, "_Peakimage.pdf"))
plotChromPeakImage(msn.rt.g) ####This function plots the number of detected peaks for each sample along the retention time axis as an image plot, i.e. with the number of peaks detected in each bin along the retention time represented with the color of the respective cell.
for(i in 1:length(fileNames(msn.rt.g))){
plotChromPeaks(msn.rt.g, file=i)
}
dev.off()

#mzr <- c(89.96725, 90.05811)
#chrs <- extractChromatograms(msn.chpeaks, mz = mzr, rt = c(500, 600))
#cols <- brewer.pal(3, "Set1")[c(1, 1, 2, 2)]
#plotChromatogram(chrs, col = paste0(cols, 80))

#chrs_adj <- extractChromatograms(msn.rt.g, mz = mzr, rt = c(500, 600))
#par(mfrow = c(2, 1))
#plot(chrs, col = paste0(cols, 80), main = "Before alignment")
#plot(chrs_adj, col = paste0(cols, 80), main = "After alignment")
```